using MetroFramework.Controls;

namespace GESTEC.BLL
{
    class ComboBox
    {
        #region Municipios
        #region 01 - Alagoas
        string[] Lista_Alagoas = new string[] {
                "Água Branca",
                "Anadia",
                "Arapiraca",
                "Atalaia",
                "Barra De Santo Antônio",
                "Barra De São Miguel",
                "Batalha",
                "Belém",
                "Belo Monte",
                "Boca Da Mata",
                "Branquinha",
                "Cacimbinhas",
                "Cajueiro",
                "Campestre",
                "Campo Alegre",
                "Campo Grande",
                "Canapi",
                "Capela",
                "Carneiros",
                "Chã Preta",
                "Coité Do Nóia",
                "Colônia Leopoldina",
                "Coqueiro Seco",
                "Coruripe",
                "Craíbas",
                "Delmiro Gouveia",
                "Dois Riachos",
                "Estrela De Alagoas",
                "Feira Grande",
                "Feliz Deserto",
                "Flexeiras",
                "Girau Do Ponciano",
                "Ibateguara",
                "Igaci",
                "Igreja Nova",
                "Inhapi",
                "Jacaré Dos Homens",
                "Jacuípe",
                "Japaratinga",
                "Jaramataia",
                "Jequiá Da Praia",
                "Joaquim Gomes",
                "Jundiá",
                "Junqueiro",
                "Lagoa Da Canoa",
                "Limoeiro De Anadia",
                "Maceió",
                "Major Isidoro",
                "Mar Vermelho",
                "Maragogi",
                "Maravilha",
                "Marechal Deodoro",
                "Maribondo",
                "Mata Grande",
                "Matriz De Camaragibe",
                "Messias",
                "Minador Do Negrão",
                "Monteirópolis",
                "Murici",
                "Novo Lino",
                "Olho D'água Das Flores",
                "Olho D'água Do Casado",
                "Olho D'água Grande",
                "Olivença",
                "Ouro Branco",
                "Palestina",
                "Palmeira Dos Índios",
                "Pão De Açúcar",
                "Pariconha",
                "Paripueira",
                "Passo De Camaragibe",
                "Paulo Jacinto",
                "Penedo",
                "Piaçabuçu",
                "Pilar",
                "Pindoba",
                "Piranhas",
                "Poço Das Trincheiras",
                "Porto Calvo",
                "Porto De Pedras",
                "Porto Real Do Colégio",
                "Quebrangulo",
                "Rio Largo",
                "Roteiro",
                "Santa Luzia Do Norte",
                "Santana Do Ipanema",
                "Santana Do Mundaú",
                "São Brás",
                "São José Da Laje",
                "São José Da Tapera",
                "São Luís Do Quitunde",
                "São Miguel Dos Campos",
                "São Miguel Dos Milagres",
                "São Sebastião",
                "Satuba",
                "Senador Rui Palmeira",
                "Tanque D'arca",
                "Taquarana",
                "Teotônio Vilela",
                "Traipu",
                "União Dos Palmares",
                "Viçosa" };
        #endregion

        #region 02 - Bahia
        string[] Lista_Bahia = new string[] {
                "Abaíra ",
                "Abaré ",
                "Acajutiba ",
                "Adustina ",
                "Água Fria ",
                "Aiquara ",
                "Alagoinhas ",
                "Alcobaça ",
                "Almadina ",
                "Amargosa ",
                "Amélia Rodrigues ",
                "América Dourada ",
                "Anagé ",
                "Andaraí ",
                "Andorinha ",
                "Angical ",
                "Anguera ",
                "Antas ",
                "Antônio Cardoso ",
                "Antônio Gonçalves ",
                "Aporá ",
                "Apuarema ",
                "Araças ",
                "Aracatu ",
                "Araci ",
                "Aramari ",
                "Arataca ",
                "Aratuípe ",
                "Aurelino Leal ",
                "Baianópolis ",
                "Baixa Grande ",
                "Banzaê ",
                "Barra ",
                "Barra Da Estiva ",
                "Barra Do Choça ",
                "Barra Do Mendes ",
                "Barra Do Rocha ",
                "Barreiras ",
                "Barro Alto ",
                "Barro Preto ",
                "Barrocas ",
                "Belmonte ",
                "Belo Campo ",
                "Biritinga ",
                "Boa Nova ",
                "Boa Vista Do Tupim ",
                "Bom Jesus Da Lapa ",
                "Bom Jesus Da Serra ",
                "Boninal ",
                "Bonito ",
                "Boquira ",
                "Botuporã ",
                "Brejões ",
                "Brejolândia ",
                "Brotas De Macaúbas ",
                "Brumado ",
                "Buerarema ",
                "Buritirama ",
                "Caatiba ",
                "Cabaceiras Do Paraguaçu ",
                "Cachoeira ",
                "Caculé ",
                "Caém ",
                "Caetanos ",
                "Caetité ",
                "Cafarnaum ",
                "Cairu ",
                "Caldeirão Grande ",
                "Camacan ",
                "Camaçari ",
                "Camamu ",
                "Campo Alegre De Lourdes ",
                "Campo Formoso ",
                "Canápolis ",
                "Canarana ",
                "Canavieiras ",
                "Candeal ",
                "Candeias ",
                "Candiba ",
                "Cândido Sales ",
                "Cansanção ",
                "Canudos ",
                "Capela Do Alto Alegre ",
                "Capim Grosso ",
                "Caraíbas ",
                "Caravelas ",
                "Cardeal Da Silva ",
                "Carinhanha ",
                "Casa Nova ",
                "Castro Alves ",
                "Catolândia ",
                "Catu ",
                "Caturama ",
                "Central ",
                "Chorrochó ",
                "Cícero Dantas ",
                "Cipó ",
                "Coaraci ",
                "Cocos ",
                "Conceição Da Feira ",
                "Conceição Do Almeida ",
                "Conceição Do Coité ",
                "Conceição Do Jacuípe ",
                "Conde ",
                "Condeúba ",
                "Contendas Do Sincorá ",
                "Coração De Maria ",
                "Cordeiros ",
                "Coribe ",
                "Coronel João Sá ",
                "Correntina ",
                "Cotegipe ",
                "Cravolândia ",
                "Crisópolis ",
                "Cristópolis ",
                "Cruz Das Almas ",
                "Curaçá ",
                "Dário Meira ",
                "Dias D'ávila ",
                "Dom Basílio ",
                "Dom Macedo Costa ",
                "Elísio Medrado ",
                "Encruzilhada ",
                "Entre Rios ",
                "Érico Cardoso ",
                "Esplanada ",
                "Euclides Da Cunha ",
                "Eunápolis ",
                "Fátima ",
                "Feira Da Mata ",
                "Feira De Santana ",
                "Filadélfia ",
                "Firmino Alves ",
                "Floresta Azul ",
                "Formosa Do Rio Preto ",
                "Gandu ",
                "Gavião ",
                "Gentio Do Ouro ",
                "Glória ",
                "Gongogi ",
                "Governador Mangabeira ",
                "Guajeru ",
                "Guanambi ",
                "Guaratinga ",
                "Heliópolis ",
                "Iaçu ",
                "Ibiassucê ",
                "Ibicaraí ",
                "Ibicoara ",
                "Ibicuí ",
                "Ibipeba ",
                "Ibipitanga ",
                "Ibiquera ",
                "Ibirapitanga ",
                "Ibirapuã ",
                "Ibirataia ",
                "Ibitiara ",
                "Ibititá ",
                "Ibotirama ",
                "Ichu ",
                "Igaporã ",
                "Igrapiúna ",
                "Iguaí ",
                "Ilhéus ",
                "Inhambupe ",
                "Ipecaetá ",
                "Ipiaú ",
                "Ipirá ",
                "Ipupiara ",
                "Irajuba ",
                "Iramaia ",
                "Iraquara ",
                "Irará ",
                "Irecê ",
                "Itabela ",
                "Itaberaba ",
                "Itabuna ",
                "Itacaré ",
                "Itaeté ",
                "Itagi ",
                "Itagibá ",
                "Itagimirim ",
                "Itaguaçu Da Bahia ",
                "Itaju Do Colônia ",
                "Itajuípe ",
                "Itamaraju ",
                "Itamari ",
                "Itambé ",
                "Itanagra ",
                "Itanhém ",
                "Itaparica ",
                "Itapé ",
                "Itapebi ",
                "Itapetinga ",
                "Itapicuru ",
                "Itapitanga ",
                "Itaquara ",
                "Itarantim ",
                "Itatim ",
                "Itiruçu ",
                "Itiúba ",
                "Itororó ",
                "Ituaçu ",
                "Ituberá ",
                "Iuiú ",
                "Jaborandi ",
                "Jacaraci ",
                "Jacobina ",
                "Jaguaquara ",
                "Jaguarari ",
                "Jaguaripe ",
                "Jandaíra ",
                "Jequié ",
                "Jeremoabo ",
                "Jiquiriçá ",
                "Jitaúna ",
                "João Dourado ",
                "Juazeiro ",
                "Jucuruçu ",
                "Jussara ",
                "Jussari ",
                "Jussiape ",
                "Lafaiete Coutinho ",
                "Lagoa Real ",
                "Laje ",
                "Lajedão ",
                "Lajedinho ",
                "Lajedo Do Tabocal ",
                "Lamarão ",
                "Lapão ",
                "Lauro De Freitas ",
                "Lençóis ",
                "Licínio De Almeida ",
                "Livramento De Nossa Senhora",
                "Luís Eduardo Magalhães ",
                "Macajuba ",
                "Macarani ",
                "Macaúbas ",
                "Macururé ",
                "Madre De Deus ",
                "Maetinga ",
                "Maiquinique ",
                "Mairi ",
                "Malhada ",
                "Malhada De Pedras ",
                "Manoel Vitorino ",
                "Mansidão ",
                "Maracás ",
                "Maragogipe ",
                "Maraú ",
                "Marcionílio Souza ",
                "Mascote ",
                "Mata De São João ",
                "Matina ",
                "Medeiros Neto ",
                "Miguel Calmon ",
                "Milagres ",
                "Mirangaba ",
                "Mirante ",
                "Monte Santo ",
                "Morpará ",
                "Morro Do Chapéu ",
                "Mortugaba ",
                "Mucugê ",
                "Mucuri ",
                "Mulungu Do Morro ",
                "Mundo Novo ",
                "Muniz Ferreira ",
                "Muquém De São Francisco ",
                "Muritiba ",
                "Mutuípe ",
                "Nazaré ",
                "Nilo Peçanha ",
                "Nordestina ",
                "Nova Canaã ",
                "Nova Fátima ",
                "Nova Ibiá ",
                "Nova Itarana ",
                "Nova Redenção ",
                "Nova Soure ",
                "Nova Viçosa ",
                "Novo Horizonte ",
                "Novo Triunfo ",
                "Olindina ",
                "Oliveira Dos Brejinhos ",
                "Ouriçangas ",
                "Ourolândia ",
                "Palmas De Monte Alto ",
                "Palmeiras ",
                "Paramirim ",
                "Paratinga ",
                "Paripiranga ",
                "Pau  ",
                "Paulo Afonso ",
                "Pé De Serra ",
                "Pedrão ",
                "Pedro Alexandre ",
                "Piatã ",
                "Pilão Arcado ",
                "Pindaí ",
                "Pindobaçu ",
                "Pintadas ",
                "Piraí Do Norte ",
                "Piripá ",
                "Piritiba ",
                "Planaltino ",
                "Planalto ",
                "Poções ",
                "Pojuca ",
                "Ponto Novo ",
                "Porto Seguro ",
                "Potiraguá ",
                "Prado ",
                "Presidente Dutra ",
                "Presidente Jânio Quadros ",
                "Presidente Tancredo Neves ",
                "Queimadas ",
                "Quijingue ",
                "Quixabeira ",
                "Rafael Jambeiro ",
                "Remanso ",
                "Retirolândia ",
                "Riachão Das Neves ",
                "Riachão Do Jacuípe ",
                "Riacho De Santana ",
                "Ribeira Do Amparo ",
                "Ribeira Do Pombal ",
                "Ribeirão Do Largo ",
                "Rio De Contas ",
                "Rio Do Antônio ",
                "Rio Do Pires ",
                "Rio Real ",
                "Rodelas ",
                "Ruy Barbosa ",
                "Salinas Da Margarida ",
                "Salvador ",
                "Santa Bárbara ",
                "Santa Brígida ",
                "Santa Cruz Cabrália ",
                "Santa Cruz Da Vitória ",
                "Santa Inês ",
                "Santa Luzia ",
                "Santa Maria Da Vitória ",
                "Santa Rita De Cássia ",
                "Santa Teresinha ",
                "Santaluz ",
                "Santana ",
                "Santanópolis ",
                "Santo Amaro ",
                "Santo Antônio De Jesus ",
                "Santo Estêvão ",
                "São Desidério ",
                "São Domingos ",
                "São Felipe ",
                "São Félix ",
                "São Félix Do Coribe ",
                "São Francisco Do Conde ",
                "São Gabriel ",
                "São Gonçalo Dos Campos ",
                "São José Da Vitória ",
                "São José Do Jacuípe ",
                "São Miguel Das Matas ",
                "São Sebastião Do Passé ",
                "Sapeaçu ",
                "Sátiro Dias ",
                "Saubara ",
                "Saúde ",
                "Seabra ",
                "Sebastião Laranjeiras ",
                "Senhor Do Bonfim ",
                "Sento Sé ",
                "Serra Do Ramalho ",
                "Serra Dourada ",
                "Serra Preta ",
                "Serrinha ",
                "Serrolândia ",
                "Simões Filho ",
                "Sítio Do Mato ",
                "Sítio Do Quinto ",
                "Sobradinho ",
                "Souto Soares ",
                "Tabocas Do Brejo Velho ",
                "Tanhaçu ",
                "Tanque Novo ",
                "Tanquinho ",
                "Taperoá ",
                "Tapiramutá ",
                "Teixeira De Freitas ",
                "Teodoro Sampaio ",
                "Teofilândia ",
                "Teolândia ",
                "Terra Nova ",
                "Tremedal ",
                "Tucano ",
                "Uauá ",
                "Ubaíra ",
                "Ubaitaba ",
                "Ubatã ",
                "Uibaí ",
                "Umburanas ",
                "Una ",
                "Urandi ",
                "Uruçuca ",
                "Utinga ",
                "Valença ",
                "Valente ",
                "Várzea Da Roça ",
                "Várzea Do Poço ",
                "Várzea Nova ",
                "Varzedo ",
                "Vera Cruz ",
                "Vereda ",
                "Vitória Da Conquista ",
                "Wagner ",
                "Wanderley ",
                "Wenceslau Guimarães ",
                "Xique-Xique" };
        #endregion

        #region 03 - Ceará
        string[] Lista_Ceara = new string[] {
            "Abaiara ",
            "Acarape ",
            "Acaraú ",
            "Acopiara ",
            "Aiuaba ",
            "Alcântaras ",
            "Altaneira ",
            "Alto Santo ",
            "Amontada ",
            "Antonina Do Norte ",
            "Apuiarés ",
            "Aquiraz ",
            "Aracati ",
            "Aracoiaba ",
            "Ararendá ",
            "Araripe ",
            "Aratuba ",
            "Arneiroz ",
            "Assaré ",
            "Aurora ",
            "Baixio ",
            "Banabuiú ",
            "Barbalha ",
            "Barreira ",
            "Barro ",
            "Barroquinha ",
            "Baturité ",
            "Beberibe ",
            "Bela Cruz ",
            "Boa Viagem ",
            "Brejo Santo ",
            "Camocim ",
            "Campos Sales ",
            "Canindé ",
            "Capistrano ",
            "Caridade ",
            "Cariré ",
            "Caririaçu ",
            "Cariús ",
            "Carnaubal ",
            "Cascavel ",
            "Catarina ",
            "Catunda ",
            "Caucaia ",
            "Cedro ",
            "Chaval ",
            "Choró ",
            "Chorozinho ",
            "Coreaú ",
            "Crateús ",
            "Crato ",
            "Croatá ",
            "Cruz ",
            "Deputado Irapuan Pinheiro ",
            "Ererê ",
            "Eusébio ",
            "Farias Brito ",
            "Forquilha ",
            "Fortaleza ",
            "Fortim ",
            "Frecheirinha ",
            "General Sampaio ",
            "Graça ",
            "Granja ",
            "Granjeiro ",
            "Groaíras ",
            "Guaiúba ",
            "Guaraciaba Do Norte ",
            "Guaramiranga ",
            "Hidrolândia ",
            "Horizonte ",
            "Ibaretama ",
            "Ibiapina ",
            "Ibicuitinga ",
            "Icapuí ",
            "Icó ",
            "Iguatu ",
            "Independência ",
            "Ipaporanga ",
            "Ipaumirim ",
            "Ipu ",
            "Ipueiras ",
            "Iracema ",
            "Irauçuba ",
            "Itaiçaba ",
            "Itaitinga ",
            "Itapagé ",
            "Itapipoca ",
            "Itapiúna ",
            "Itarema ",
            "Itatira ",
            "Jaguaretama ",
            "Jaguaribara ",
            "Jaguaribe ",
            "Jaguaruana ",
            "Jardim ",
            "Jati ",
            "Jijoca De Jericoacoara ",
            "Juazeiro Do Norte ",
            "Jucás ",
            "Lavras Da Mangabeira ",
            "Limoeiro Do Norte ",
            "Madalena ",
            "Maracanaú ",
            "Maranguape ",
            "Marco ",
            "Martinópole ",
            "Massapê ",
            "Mauriti ",
            "Meruoca ",
            "Milagres ",
            "Milhã ",
            "Miraíma ",
            "Missão Velha ",
            "Mombaça ",
            "Monsenhor Tabosa ",
            "Morada Nova ",
            "Moraújo ",
            "Morrinhos ",
            "Mucambo ",
            "Mulungu ",
            "Nova Olinda ",
            "Nova Russas ",
            "Novo Oriente ",
            "Ocara ",
            "Orós ",
            "Pacajus ",
            "Pacatuba ",
            "Pacoti ",
            "Pacujá ",
            "Palhano ",
            "Palmácia ",
            "Paracuru ",
            "Paraipaba ",
            "Parambu ",
            "Paramoti ",
            "Pedra Branca ",
            "Penaforte ",
            "Pentecoste ",
            "Pereiro ",
            "Pindoretama ",
            "Piquet Carneiro ",
            "Pires Ferreira ",
            "Poranga ",
            "Porteiras ",
            "Potengi ",
            "Potiretama ",
            "Quiterianópolis ",
            "Quixadá ",
            "Quixelô ",
            "Quixeramobim ",
            "Quixeré ",
            "Redenção ",
            "Reriutaba ",
            "Russas ",
            "Saboeiro ",
            "Salitre ",
            "Santa Quitéria ",
            "Santana Do Acaraú ",
            "Santana Do Cariri ",
            "São Benedito ",
            "São Gonçalo Do Amarante ",
            "São João Do Jaguaribe ",
            "São Luís Do Curu ",
            "Senador Pompeu ",
            "Senador Sá ",
            "Sobral ",
            "Solonópole ",
            "Tabuleiro Do Norte ",
            "Tamboril ",
            "Tarrafas ",
            "Tauá ",
            "Tejuçuoca ",
            "Tianguá ",
            "Trairi ",
            "Tururu ",
            "Ubajara ",
            "Umari ",
            "Umirim ",
            "Uruburetama ",
            "Uruoca ",
            "Varjota ",
            "Várzea Alegre ",
            "Viçosa Do Ceará" };
        #endregion

        #region 04 - Maranhão
        string[] Lista_Maranhao = new string[] {
            "Açailândia ",
            "Afonso Cunha ",
            "Água Doce Do Maranhão ",
            "Alcântara ",
            "Aldeias Altas ",
            "Altamira Do Maranhão ",
            "Alto Alegre Do Maranhão ",
            "Alto Alegre Do Pindaré ",
            "Alto Parnaíba ",
            "Amapá Do Maranhão ",
            "Amarante Do Maranhão ",
            "Anajatuba ",
            "Anapurus ",
            "Apicum-Açu ",
            "Araguanã ",
            "Araioses ",
            "Arame ",
            "Arari ",
            "Axixá ",
            "Bacabal ",
            "Bacabeira ",
            "Bacuri ",
            "Bacurituba ",
            "Balsas ",
            "Barão De Grajaú ",
            "Barra Do Corda ",
            "Barreirinhas ",
            "Bela Vista Do Maranhão ",
            "Belágua ",
            "Benedito Leite ",
            "Bequimão ",
            "Bernardo Do Mearim ",
            "Boa Vista Do Gurupi ",
            "Bom Jardim ",
            "Bom Jesus Das Selvas ",
            "Bom Lugar ",
            "Brejo ",
            "Brejo De Areia ",
            "Buriti ",
            "Buriti Bravo ",
            "Buriticupu ",
            "Buritirana ",
            "Cachoeira Grande ",
            "Cajapió ",
            "Cajari ",
            "Campestre Do Maranhão ",
            "Cândido Mendes ",
            "Cantanhede ",
            "Capinzal Do Norte ",
            "Carolina ",
            "Carutapera ",
            "Caxias ",
            "Cedral ",
            "Central Do Maranhão ",
            "Centro Do Guilherme ",
            "Centro Novo Do Maranhão ",
            "Chapadinha ",
            "Cidelândia ",
            "Codó ",
            "Coelho Neto ",
            "Colinas ",
            "Conceição Do Lago-Açu ",
            "Coroatá ",
            "Cururupu ",
            "Davinópolis ",
            "Dom Pedro ",
            "Duque Bacelar ",
            "Esperantinópolis ",
            "Estreito ",
            "Feira Nova Do Maranhão ",
            "Fernando Falcão ",
            "Formosa Da Serra Negra ",
            "Fortaleza Dos Nogueiras ",
            "Fortuna ",
            "Godofredo Viana ",
            "Gonçalves Dias ",
            "Governador Archer ",
            "Governador Edison Lobão ",
            "Governador Eugênio Barros ",
            "Governador Luiz Rocha ",
            "Governador Newton Bello ",
            "Governador Nunes Freire ",
            "Graça Aranha ",
            "Grajaú ",
            "Guimarães ",
            "Humberto De Campos ",
            "Icatu ",
            "Igarapé Do Meio ",
            "Igarapé Grande ",
            "Imperatriz ",
            "Itaipava Do Grajaú ",
            "Itapecuru Mirim ",
            "Itinga Do Maranhão ",
            "Jatobá ",
            "Jenipapo Dos Vieiras ",
            "João Lisboa ",
            "Joselândia ",
            "Junco Do Maranhão ",
            "Lago Da Pedra ",
            "Lago Do Junco ",
            "Lago Dos Rodrigues ",
            "Lago Verde ",
            "Lagoa Do Mato ",
            "Lagoa Grande Do Maranhão ",
            "Lajeado Novo ",
            "Lima Campos ",
            "Loreto ",
            "Luís Domingues ",
            "Magalhães De Almeida ",
            "Maracaçumé ",
            "Marajá Do Sena ",
            "Maranhãozinho ",
            "Mata Roma ",
            "Matinha ",
            "Matões ",
            "Matões Do Norte ",
            "Milagres Do Maranhão ",
            "Mirador ",
            "Miranda Do Norte ",
            "Mirinzal ",
            "Monção ",
            "Montes Altos ",
            "Morros ",
            "Nina Rodrigues ",
            "Nova Colinas ",
            "Nova Iorque ",
            "Nova Olinda Do Maranhão ",
            "Olho D'água Das Cunhãs ",
            "Olinda Nova Do Maranhão ",
            "Paço Do Lumiar ",
            "Palmeirândia ",
            "Paraibano ",
            "Parnarama ",
            "Passagem Franca ",
            "Pastos Bons ",
            "Paulino Neves ",
            "Paulo Ramos ",
            "Pedreiras ",
            "Pedro Do Rosário ",
            "Penalva ",
            "Peri Mirim ",
            "Peritoró ",
            "Pindaré-Mirim ",
            "Pinheiro ",
            "Pio Xii ",
            "Pirapemas ",
            "Poção De Pedras ",
            "Porto Franco ",
            "Porto Rico Do Maranhão ",
            "Presidente Dutra ",
            "Presidente Juscelino ",
            "Presidente Médici ",
            "Presidente Sarney ",
            "Presidente Vargas ",
            "Primeira Cruz ",
            "Raposa ",
            "Riachão ",
            "Ribamar Fiquene ",
            "Rosário ",
            "Sambaíba ",
            "Santa Filomena Do Maranhão ",
            "Santa Helena ",
            "Santa Inês ",
            "Santa Luzia ",
            "Santa Luzia Do Paruá ",
            "Santa Quitéria Do Maranhão ",
            "Santa Rita ",
            "Santana Do Maranhão ",
            "Santo Amaro Do Maranhão ",
            "Santo Antônio Dos Lopes ",
            "São Benedito Do Rio Preto ",
            "São Bento ",
            "São Bernardo ",
            "São Domingos Do Azeitão ",
            "São Domingos Do Maranhão ",
            "São Félix De Balsas ",
            "São Francisco Do Brejão ",
            "São Francisco Do Maranhão ",
            "São João Batista ",
            "São João Do Carú ",
            "São João Do Paraíso ",
            "São João Do Soter ",
            "São João Dos Patos ",
            "São José De Ribamar ",
            "São José Dos Basílios ",
            "São Luís ",
            "São Luís Gonzaga Do Maranhão ",
            "São Mateus Do Maranhão ",
            "São Pedro Da Água Branca ",
            "São Pedro Dos Crentes ",
            "São Raimundo Das Mangabeiras ",
            "São Raimundo Do Doca Bezerra ",
            "São Roberto ",
            "São Vicente Ferrer ",
            "Satubinha ",
            "Senador Alexandre Costa ",
            "Senador La Rocque ",
            "Serrano Do Maranhão ",
            "Sítio Novo ",
            "Sucupira Do Norte ",
            "Sucupira Do Riachão ",
            "Tasso Fragoso ",
            "Timbiras ",
            "Timon ",
            "Trizidela Do Vale ",
            "Tufilândia ",
            "Tuntum ",
            "Turiaçu ",
            "Turilândia ",
            "Tutóia ",
            "Urbano Santos ",
            "Vargem Grande ",
            "Viana ",
            "Vila Nova Dos Martírios ",
            "Vitória Do Mearim ",
            "Vitorino Freire ",
            "Zé Doca "};
        #endregion

        #region 05 - Paraíba
        string[] Lista_Paraiba = new string[] {
            "Água Branca ",
            "Aguiar ",
            "Alagoa Grande ",
            "Alagoa Nova ",
            "Alagoinha ",
            "Alcantil ",
            "Algodão De Jandaíra ",
            "Alhandra ",
            "Amparo ",
            "Aparecida ",
            "Araçagi ",
            "Arara ",
            "Araruna ",
            "Areia ",
            "Areia De Baraúnas ",
            "Areial ",
            "Aroeiras ",
            "Assunção ",
            "Baía Da Traição ",
            "Bananeiras ",
            "Baraúna ",
            "Barra De Santa Rosa ",
            "Barra De Santana ",
            "Barra De São Miguel ",
            "Bayeux ",
            "Belém ",
            "Belém Do Brejo Do Cruz ",
            "Bernardino Batista ",
            "Boa Ventura ",
            "Boa Vista ",
            "Bom Jesus ",
            "Bom Sucesso ",
            "Bonito De Santa Fé ",
            "Boqueirão ",
            "Borborema ",
            "Brejo Do Cruz ",
            "Brejo Dos Santos ",
            "Caaporã ",
            "Cabaceiras ",
            "Cabedelo ",
            "Cachoeira Dos Índios ",
            "Cacimba De Areia ",
            "Cacimba De Dentro ",
            "Cacimbas ",
            "Caiçara ",
            "Cajazeiras ",
            "Cajazeirinhas ",
            "Caldas Brandão ",
            "Camalaú ",
            "Campina Grande ",
            "Capim ",
            "Caraúbas ",
            "Carrapateira ",
            "Casserengue ",
            "Catingueira ",
            "Catolé Do Rocha ",
            "Caturité ",
            "Conceição ",
            "Condado ",
            "Conde ",
            "Congo ",
            "Coremas ",
            "Coxixola ",
            "Cruz Do Espírito Santo ",
            "Cubati ",
            "Cuité ",
            "Cuité De Mamanguape ",
            "Cuitegi ",
            "Curral De Cima ",
            "Curral Velho ",
            "Damião ",
            "Desterro ",
            "Diamante ",
            "Dona Inês ",
            "Duas Estradas ",
            "Emas ",
            "Esperança ",
            "Fagundes ",
            "Frei Martinho ",
            "Gado Bravo ",
            "Guarabira ",
            "Gurinhém ",
            "Gurjão ",
            "Ibiara ",
            "Igaracy ",
            "Imaculada ",
            "Ingá ",
            "Itabaiana ",
            "Itaporanga ",
            "Itapororoca ",
            "Itatuba ",
            "Jacaraú ",
            "Jericó ",
            "João Pessoa ",
            "Joca Claudino ",
            "Juarez Távora ",
            "Juazeirinho ",
            "Junco Do Seridó ",
            "Juripiranga ",
            "Juru ",
            "Lagoa ",
            "Lagoa De Dentro ",
            "Lagoa Seca ",
            "Lastro ",
            "Livramento ",
            "Logradouro ",
            "Lucena ",
            "Mãe D'água ",
            "Malta ",
            "Mamanguape ",
            "Manaíra ",
            "Marcação ",
            "Mari ",
            "Marizópolis ",
            "Massaranduba ",
            "Mataraca ",
            "Matinhas ",
            "Mato Grosso ",
            "Maturéia ",
            "Mogeiro ",
            "Montadas ",
            "Monte Horebe ",
            "Monteiro ",
            "Mulungu ",
            "Natuba ",
            "Nazarezinho ",
            "Nova Floresta ",
            "Nova Olinda ",
            "Nova Palmeira ",
            "Olho D'água ",
            "Olivedos ",
            "Ouro Velho ",
            "Parari ",
            "Passagem ",
            "Patos ",
            "Paulista ",
            "Pedra Branca ",
            "Pedra Lavrada ",
            "Pedras De Fogo ",
            "Pedro Régis ",
            "Piancó ",
            "Picuí ",
            "Pilar ",
            "Pilões ",
            "Pilõezinhos ",
            "Pirpirituba ",
            "Pitimbu ",
            "Pocinhos ",
            "Poço Dantas ",
            "Poço De José De Moura ",
            "Pombal ",
            "Prata ",
            "Princesa Isabel ",
            "Puxinanã ",
            "Queimadas ",
            "Quixabá ",
            "Remígio ",
            "Riachão ",
            "Riachão Do Bacamarte ",
            "Riachão Do Poço ",
            "Riacho De Santo Antônio ",
            "Riacho Dos Cavalos ",
            "Rio Tinto ",
            "Salgadinho ",
            "Salgado De São Félix ",
            "Santa Cecília ",
            "Santa Cruz ",
            "Santa Helena ",
            "Santa Inês ",
            "Santa Luzia ",
            "Santa Rita ",
            "Santa Teresinha ",
            "Santana De Mangueira ",
            "Santana Dos Garrotes ",
            "Santo André ",
            "São Bentinho ",
            "São Bento ",
            "São Domingos De Pombal ",
            "São Domingos Do Cariri ",
            "São Francisco ",
            "São João Do Cariri ",
            "São João Do Rio Do Peixe ",
            "São João Do Tigre ",
            "São José Da Lagoa Tapada ",
            "São José De Caiana ",
            "São José De Espinharas ",
            "São José De Piranhas ",
            "São José De Princesa ",
            "São José Do Bonfim ",
            "São José Do Brejo Do Cruz ",
            "São José Do Sabugi ",
            "São José Dos Cordeiros ",
            "São José Dos Ramos ",
            "São Mamede ",
            "São Miguel De Taipu ",
            "São Sebastião De Lagoa De Roça ",
            "São Sebastião Do Umbuzeiro ",
            "Sapé ",
            "Seridó ",
            "Serra Branca ",
            "Serra Da Raiz ",
            "Serra Grande ",
            "Serra Redonda ",
            "Serraria ",
            "Sertãozinho ",
            "Sobrado ",
            "Solânea ",
            "Soledade ",
            "Sossêgo ",
            "Sousa ",
            "Sumé ",
            "Tacima ",
            "Taperoá ",
            "Tavares ",
            "Teixeira ",
            "Tenório ",
            "Triunfo ",
            "Uiraúna ",
            "Umbuzeiro ",
            "Várzea ",
            "Vieirópolis ",
            "Vista Serrana ",
            "Zabelê" };
        #endregion

        #region 06 - Pernambuco
        string[] Lista_Pernambuco = new string[] {
            "Abreu E Lima ",
            "Afogados Da Ingazeira ",
            "Afrânio ",
            "Agrestina ",
            "Água Preta ",
            "Águas Belas ",
            "Alagoinha ",
            "Aliança ",
            "Altinho ",
            "Amaraji ",
            "Angelim ",
            "Araçoiaba ",
            "Araripina ",
            "Arcoverde ",
            "Barra De Guabiraba ",
            "Barreiros ",
            "Belém De Maria ",
            "Belém De São Francisco ",
            "Belo Jardim ",
            "Betânia ",
            "Bezerros ",
            "Bodocó ",
            "Bom Conselho ",
            "Bom Jardim ",
            "Bonito ",
            "Brejão ",
            "Brejinho ",
            "Brejo Da Madre De Deus ",
            "Buenos Aires ",
            "Buíque ",
            "Cabo De Santo Agostinho ",
            "Cabrobó ",
            "Cachoeirinha ",
            "Caetés ",
            "Calçado ",
            "Calumbi ",
            "Camaragibe ",
            "Camocim De São Félix ",
            "Camutanga ",
            "Canhotinho ",
            "Capoeiras ",
            "Carnaíba ",
            "Carnaubeira Da Penha ",
            "Carpina ",
            "Caruaru ",
            "Casinhas ",
            "Catende ",
            "Cedro ",
            "Chã De Alegria ",
            "Chã Grande ",
            "Condado ",
            "Correntes ",
            "Cortês ",
            "Cumaru ",
            "Cupira ",
            "Custódia ",
            "Dormentes ",
            "Escada ",
            "Exu ",
            "Feira Nova ",
            "Fernando De Noronha ",
            "Ferreiros ",
            "Flores ",
            "Floresta ",
            "Frei Miguelinho ",
            "Gameleira ",
            "Garanhuns ",
            "Glória Do Goitá ",
            "Goiana ",
            "Granito ",
            "Gravatá ",
            "Iati ",
            "Ibimirim ",
            "Ibirajuba ",
            "Igarassu ",
            "Iguaraci ",
            "Ilha De Itamaracá ",
            "Inajá ",
            "Ingazeira ",
            "Ipojuca ",
            "Ipubi ",
            "Itacuruba ",
            "Itaíba ",
            "Itambé ",
            "Itapetim ",
            "Itapissuma ",
            "Itaquitinga ",
            "Jaboatão Dos Guararapes ",
            "Jaqueira ",
            "Jataúba ",
            "Jatobá ",
            "João Alfredo ",
            "Joaquim Nabuco ",
            "Jucati ",
            "Jupi ",
            "Jurema ",
            "Lagoa Do Carro ",
            "Lagoa Do Itaenga ",
            "Lagoa Do Ouro ",
            "Lagoa Dos Gatos ",
            "Lagoa Grande ",
            "Lajedo ",
            "Limoeiro ",
            "Macaparana ",
            "Machados ",
            "Manari ",
            "Maraial ",
            "Mirandiba ",
            "Moreilândia ",
            "Moreno ",
            "Nazaré Da Mata ",
            "Olinda ",
            "Orobó ",
            "Orocó ",
            "Ouricuri ",
            "Palmares ",
            "Palmeirina ",
            "Panelas ",
            "Paranatama ",
            "Parnamirim ",
            "Passira ",
            "Paudalho ",
            "Paulista ",
            "Pedra ",
            "Pesqueira ",
            "Petrolândia ",
            "Petrolina ",
            "Poção ",
            "Pombos ",
            "Primavera ",
            "Quipapá ",
            "Quixaba ",
            "Recife ",
            "Riacho Das Almas ",
            "Ribeirão ",
            "Rio Formoso ",
            "Sairé ",
            "Salgadinho ",
            "Salgueiro ",
            "Saloá ",
            "Sanharó ",
            "Santa Cruz ",
            "Santa Cruz Da Baixa Verde ",
            "Santa Cruz Do Capibaribe ",
            "Santa Filomena ",
            "Santa Maria Da Boa Vista ",
            "Santa Maria Do Cambucá ",
            "Santa Terezinha ",
            "São Benedito Do Sul ",
            "São Bento Do Una ",
            "São Caitano ",
            "São João ",
            "São Joaquim Do Monte ",
            "São José Da Coroa Grande ",
            "São José Do Belmonte ",
            "São José Do Egito ",
            "São Lourenço Da Mata ",
            "São Vicente Ferrer ",
            "Serra Talhada ",
            "Serrita ",
            "Sertânia ",
            "Sirinhaém ",
            "Solidão ",
            "Surubim ",
            "Tabira ",
            "Tacaimbó ",
            "Tacaratu ",
            "Tamandaré ",
            "Taquaritinga Do Norte ",
            "Terezinha ",
            "Terra Nova ",
            "Timbaúba ",
            "Toritama ",
            "Tracunhaém ",
            "Trindade ",
            "Triunfo ",
            "Tupanatinga ",
            "Tuparetama ",
            "Venturosa ",
            "Verdejante ",
            "Vertente Do Lério ",
            "Vertentes ",
            "Vicência ",
            "Vitória De Santo Antão ",
            "Xexéu" };
        #endregion

        #region 07 - Piauí
        string[] Lista_Piaui = new string[] {
            "Acauã ",
            "Agricolândia ",
            "Água Branca ",
            "Alagoinha Do Piauí ",
            "Alegrete Do Piauí ",
            "Alto Longá ",
            "Altos ",
            "Alvorada Do Gurguéia ",
            "Amarante ",
            "Angical Do Piauí ",
            "Anísio De Abreu ",
            "Antônio Almeida ",
            "Aroazes ",
            "Aroeiras Do Itaim ",
            "Arraial ",
            "Assunção Do Piauí ",
            "Avelino Lopes ",
            "Baixa Grande Do Ribeiro ",
            "Barra D'alcântara ",
            "Barras ",
            "Barreiras Do Piauí ",
            "Barro Duro ",
            "Batalha ",
            "Bela Vista Do Piauí ",
            "Belém Do Piauí ",
            "Beneditinos ",
            "Bertolínia ",
            "Betânia Do Piauí ",
            "Boa Hora ",
            "Bocaina ",
            "Bom Jesus ",
            "Bom Princípio Do Piauí ",
            "Bonfim Do Piauí ",
            "Boqueirão Do Piauí ",
            "Brasileira ",
            "Brejo Do Piauí ",
            "Buriti Dos Lopes ",
            "Buriti Dos Montes ",
            "Cabeceiras Do Piauí ",
            "Cajazeiras Do Piauí ",
            "Cajueiro Da Praia ",
            "Caldeirão Grande Do Piauí ",
            "Campinas Do Piauí ",
            "Campo Alegre Do Fidalgo ",
            "Campo Grande Do Piauí ",
            "Campo Largo Do Piauí ",
            "Campo Maior ",
            "Canavieira ",
            "Canto Do Buriti ",
            "Capitão De Campos ",
            "Capitão Gervásio Oliveira ",
            "Caracol ",
            "Caraúbas Do Piauí ",
            "Caridade Do Piauí ",
            "Castelo Do Piauí ",
            "Caxingó ",
            "Cocal ",
            "Cocal De Telha ",
            "Cocal Dos Alves ",
            "Coivaras ",
            "Colônia Do Gurguéia ",
            "Colônia Do Piauí ",
            "Conceição Do Canindé ",
            "Coronel José Dias ",
            "Corrente ",
            "Cristalândia Do Piauí ",
            "Cristino Castro ",
            "Curimatá ",
            "Currais ",
            "Curral Novo Do Piauí ",
            "Curralinhos ",
            "Demerval Lobão ",
            "Dirceu Arcoverde ",
            "Dom Expedito Lopes ",
            "Dom Inocêncio ",
            "Domingos Mourão ",
            "Elesbão Veloso ",
            "Eliseu Martins ",
            "Esperantina ",
            "Fartura Do Piauí ",
            "Flores Do Piauí ",
            "Floresta Do Piauí ",
            "Floriano ",
            "Francinópolis ",
            "Francisco Ayres ",
            "Francisco Macedo ",
            "Francisco Santos ",
            "Fronteiras ",
            "Geminiano ",
            "Gilbués ",
            "Guadalupe ",
            "Guaribas ",
            "Hugo Napoleão ",
            "Ilha Grande ",
            "Inhuma ",
            "Ipiranga Do Piauí ",
            "Isaías Coelho ",
            "Itainópolis ",
            "Itaueira ",
            "Jacobina Do Piauí ",
            "Jaicós ",
            "Jardim Do Mulato ",
            "Jatobá Do Piauí ",
            "Jerumenha ",
            "João Costa ",
            "Joaquim Pires ",
            "Joca Marques ",
            "José De Freitas ",
            "Juazeiro Do Piauí ",
            "Júlio Borges ",
            "Jurema ",
            "Lagoa Alegre ",
            "Lagoa De São Francisco ",
            "Lagoa Do Barro Do Piauí ",
            "Lagoa Do Piauí ",
            "Lagoa Do Sítio ",
            "Lagoinha Do Piauí ",
            "Landri Sales ",
            "Luís Correia ",
            "Luzilândia ",
            "Madeiro ",
            "Manoel Emídio ",
            "Marcolândia ",
            "Marcos Parente ",
            "Massapê Do Piauí ",
            "Matias Olímpio ",
            "Miguel Alves ",
            "Miguel Leão ",
            "Milton Brandão ",
            "Monsenhor Gil ",
            "Monsenhor Hipólito ",
            "Monte Alegre Do Piauí ",
            "Morro Cabeça No Tempo ",
            "Morro Do Chapéu Do Piauí ",
            "Murici Dos Portelas ",
            "Nazaré Do Piauí ",
            "Nazária ",
            "Nossa Senhora De Nazaré ",
            "Nossa Senhora Dos Remédios",
            "Nova Santa Rita ",
            "Novo Oriente Do Piauí ",
            "Novo Santo Antônio ",
            "Oeiras ",
            "Olho D'água Do Piauí ",
            "Padre Marcos ",
            "Paes Landim ",
            "Pajeú Do Piauí ",
            "Palmeira Do Piauí ",
            "Palmeirais ",
            "Paquetá ",
            "Parnaguá ",
            "Parnaíba ",
            "Passagem Franca Do Piauí ",
            "Patos Do Piauí ",
            "Pau D'arco Do Piauí ",
            "Paulistana ",
            "Pavussu ",
            "Pedro Ii ",
            "Pedro Laurentino ",
            "Picos ",
            "Pimenteiras ",
            "Pio Ix ",
            "Piracuruca ",
            "Piripiri ",
            "Porto ",
            "Porto Alegre Do Piauí ",
            "Prata Do Piauí ",
            "Queimada Nova ",
            "Redenção Do Gurguéia ",
            "Regeneração ",
            "Riacho Frio ",
            "Ribeira Do Piauí ",
            "Ribeiro Gonçalves ",
            "Rio Grande Do Piauí ",
            "Santa Cruz Do Piauí ",
            "Santa Cruz Dos Milagres ",
            "Santa Filomena ",
            "Santa Luz ",
            "Santa Rosa Do Piauí ",
            "Santana Do Piauí ",
            "Santo Antônio De Lisboa ",
            "Santo Antônio Dos Milagres ",
            "Santo Inácio Do Piauí ",
            "São Braz Do Piauí ",
            "São Félix Do Piauí ",
            "São Francisco De Assis Do Piauí ",
            "São Francisco Do Piauí ",
            "São Gonçalo Do Gurguéia ",
            "São Gonçalo Do Piauí ",
            "São João Da Canabrava ",
            "São João Da Fronteira ",
            "São João Da Serra ",
            "São João Da Varjota ",
            "São João Do Arraial ",
            "São João Do Piauí ",
            "São José Do Divino ",
            "São José Do Peixe ",
            "São José Do Piauí ",
            "São Julião ",
            "São Lourenço Do Piauí ",
            "São Luis Do Piauí ",
            "São Miguel Da Baixa Grande ",
            "São Miguel Do Fidalgo ",
            "São Miguel Do Tapuio ",
            "São Pedro Do Piauí ",
            "São Raimundo Nonato ",
            "Sebastião Barros ",
            "Sebastião Leal ",
            "Sigefredo Pacheco ",
            "Simões ",
            "Simplício Mendes ",
            "Socorro Do Piauí ",
            "Sussuapara ",
            "Tamboril Do Piauí ",
            "Tanque Do Piauí ",
            "Teresina ",
            "União ",
            "Uruçuí ",
            "Valença Do Piauí ",
            "Várzea Branca ",
            "Várzea Grande ",
            "Vera Mendes ",
            "Vila Nova Do Piauí ",
            "Wall Ferraz" };
        #endregion

        #region 08 - Rio Grande do Norte
        string[] Lista_RioGrandeNorte = new string[] {
            "Acari ",
            "Açu ",
            "Afonso Bezerra ",
            "Água Nova ",
            "Alexandria ",
            "Almino Afonso ",
            "Alto Do Rodrigues ",
            "Angicos ",
            "Antônio Martins ",
            "Apodi ",
            "Areia Branca ",
            "Arês ",
            "Augusto Severo ",
            "Baía Formosa ",
            "Baraúna ",
            "Barcelona ",
            "Bento Fernandes ",
            "Bodó ",
            "Bom Jesus ",
            "Brejinho ",
            "Caiçara Do Norte ",
            "Caiçara Do Rio Do Vento ",
            "Caicó ",
            "Campo Redondo ",
            "Canguaretama ",
            "Caraúbas ",
            "Carnaúba Dos Dantas ",
            "Carnaubais ",
            "Ceará-Mirim ",
            "Cerro Corá ",
            "Coronel Ezequiel ",
            "Coronel João Pessoa ",
            "Cruzeta ",
            "Currais Novos ",
            "Doutor Severiano ",
            "Encanto ",
            "Equador ",
            "Espírito Santo ",
            "Extremoz ",
            "Felipe Guerra ",
            "Fernando Pedroza ",
            "Florânia ",
            "Francisco Dantas ",
            "Frutuoso Gomes ",
            "Galinhos ",
            "Goianinha ",
            "Governador Dix-Sept Rosado ",
            "Grossos ",
            "Guamaré ",
            "Ielmo Marinho ",
            "Ipanguaçu ",
            "Ipueira ",
            "Itajá ",
            "Itaú ",
            "Jaçanã ",
            "Jandaíra ",
            "Janduís ",
            "Januário Cicco ",
            "Japi ",
            "Jardim De Angicos ",
            "Jardim De Piranhas ",
            "Jardim Do Seridó ",
            "João Câmara ",
            "João Dias ",
            "José Da Penha ",
            "Jucurutu ",
            "Jundiá ",
            "Lagoa D'anta ",
            "Lagoa De Pedras ",
            "Lagoa De Velhos ",
            "Lagoa Nova ",
            "Lagoa Salgada ",
            "Lajes ",
            "Lajes Pintadas ",
            "Lucrécia ",
            "Luís Gomes ",
            "Macaíba ",
            "Macau ",
            "Major Sales ",
            "Marcelino Vieira ",
            "Martins ",
            "Maxaranguape ",
            "Messias Targino ",
            "Montanhas ",
            "Monte Alegre ",
            "Monte Das Gameleiras ",
            "Mossoró ",
            "Natal ",
            "Nísia Floresta ",
            "Nova Cruz ",
            "Olho-D'água Do Borges ",
            "Ouro Branco ",
            "Paraná ",
            "Paraú ",
            "Parazinho ",
            "Parelhas ",
            "Parnamirim ",
            "Passa E Fica ",
            "Passagem ",
            "Patu ",
            "Pau Dos Ferros ",
            "Pedra Grande ",
            "Pedra Preta ",
            "Pedro Avelino ",
            "Pedro Velho ",
            "Pendências ",
            "Pilões ",
            "Poço Branco ",
            "Portalegre ",
            "Porto Do Mangue ",
            "Presidente Juscelino ",
            "Pureza ",
            "Rafael Fernandes ",
            "Rafael Godeiro ",
            "Riacho Da Cruz ",
            "Riacho De Santana ",
            "Riachuelo ",
            "Rio Do Fogo ",
            "Rodolfo Fernandes ",
            "Ruy Barbosa ",
            "Santa Cruz ",
            "Santa Maria ",
            "Santana Do Matos ",
            "Santana Do Seridó ",
            "Santo Antônio ",
            "São Bento Do Norte ",
            "São Bento Do Trairí ",
            "São Fernando ",
            "São Francisco Do Oeste ",
            "São Gonçalo Do Amarante ",
            "São João Do Sabugi ",
            "São José De Mipibu ",
            "São José Do Campestre ",
            "São José Do Seridó ",
            "São Miguel ",
            "São Miguel Do Gostoso ",
            "São Paulo Do Potengi ",
            "São Pedro ",
            "São Rafael ",
            "São Tomé ",
            "São Vicente ",
            "Senador Elói De Souza ",
            "Senador Georgino Avelino ",
            "Serra De São Bento ",
            "Serra Do Mel ",
            "Serra Negra Do Norte ",
            "Serrinha ",
            "Serrinha Dos Pintos ",
            "Severiano Melo ",
            "Sítio Novo ",
            "Taboleiro Grande ",
            "Taipu ",
            "Tangará ",
            "Tenente Ananias ",
            "Tenente Laurentino Cruz ",
            "Tibau ",
            "Tibau Do Sul ",
            "Timbaúba Dos Batistas ",
            "Touros ",
            "Triunfo Potiguar ",
            "Umarizal ",
            "Upanema ",
            "Várzea ",
            "Venha-Ver ",
            "Vera Cruz ",
            "Viçosa ",
            "Vila Flor" };
        #endregion

        #region 09 - Sergipe
        string[] Lista_Sergipe = new string[] {
            "Amparo De São Francisco ",
            "Aquidabã ",
            "Aracaju ",
            "Arauá ",
            "Areia Branca ",
            "Barra Dos Coqueiros ",
            "Boquim ",
            "Brejo Grande ",
            "Campo Do Brito ",
            "Canhoba ",
            "Canindé De São Francisco ",
            "Capela ",
            "Carira ",
            "Carmópolis ",
            "Cedro De São João ",
            "Cristinápolis ",
            "Cumbe ",
            "Divina Pastora ",
            "Estância ",
            "Feira Nova ",
            "Frei Paulo ",
            "Gararu ",
            "General Maynard ",
            "Gracho Cardoso ",
            "Ilha Das Flores ",
            "Indiaroba ",
            "Itabaiana ",
            "Itabaianinha ",
            "Itabi ",
            "Itaporanga D'ajuda ",
            "Japaratuba ",
            "Japoatã ",
            "Lagarto ",
            "Laranjeiras ",
            "Macambira ",
            "Malhada Dos Bois ",
            "Malhador ",
            "Maruim ",
            "Moita Bonita ",
            "Monte Alegre De Sergipe ",
            "Muribeca ",
            "Neópolis ",
            "Nossa Senhora Aparecida ",
            "Nossa Senhora Da Glória ",
            "Nossa Senhora Das Dores ",
            "Nossa Senhora De Lourdes ",
            "Nossa Senhora Do Socorro ",
            "Pacatuba ",
            "Pedra Mole ",
            "Pedrinhas ",
            "Pinhão ",
            "Pirambu ",
            "Poço Redondo ",
            "Poço Verde ",
            "Porto Da Folha ",
            "Propriá ",
            "Riachão Do Dantas ",
            "Riachuelo ",
            "Ribeirópolis ",
            "Rosário Do Catete ",
            "Salgado ",
            "Santa Luzia Do Itanhy ",
            "Santa Rosa De Lima ",
            "Santana Do São Francisco ",
            "Santo Amaro Das Brotas ",
            "São Cristóvão ",
            "São Domingos ",
            "São Francisco ",
            "São Miguel Do Aleixo ",
            "Simão Dias ",
            "Siriri ",
            "Telha ",
            "Tobias Barreto ",
            "Tomar Do Geru ",
            "Umbaúba" };
        #endregion
        #endregion

        #region Estados
        public void Estados(MetroComboBox cbbEstado)
        {
            // Criamos um Array do tipo string e colocamos algumas Unidades Federativas 
            string[] ListaUF = new string[] {
                                              "Alagoas – AL",
                                              "Bahia – BA",
                                              "Ceará – CE",
                                              "Maranhão – MA",
                                              "Paraíba – PB",
                                              "Pernambuco – PE",
                                              "Piauí – PI",
                                              "Rio Grande do Norte – RN",
                                              "Sergipe – SE", };

            //  fizemos um foreach para percorrer cada item existente na lista ListaUF  
            foreach (var x in ListaUF)
            {
                // aqui estamos adicionando os itens no combobox
                cbbEstado.Items.Add(x);
            }
        }
        #endregion
      
        #region Verifica EstadoSelecionado
        public void VerificaEstado(MetroComboBox cbbEstado, MetroComboBox cbbMunicipio)
        {         
            //Verifica Index:
            if (cbbEstado.Text == "Alagoas – AL")
            {
                cbbMunicipio.Items.Clear();
                //Foreach
                foreach (var x in Lista_Alagoas)
                {
                    //Adiciona itens no combobox:
                    
                    cbbMunicipio.Items.Add(x);
                }
            }

            else if (cbbEstado.Text == "Bahia – BA")
            {
                cbbMunicipio.Items.Clear();
                //Foreach
                foreach (var x in Lista_Bahia)
                {
                    //Adiciona itens no combobox:
                    cbbMunicipio.Items.Add(x);
                }
            }

            else if (cbbEstado.Text == "Ceará – CE")
            {
                cbbMunicipio.Items.Clear();
                //Foreach
                foreach (var x in Lista_Ceara)
                {
                    //Adiciona itens no combobox:
                    cbbMunicipio.Items.Add(x);
                }
            }

            else if (cbbEstado.Text == "Maranhão – MA")
            {
                cbbMunicipio.Items.Clear();
                //Foreach
                foreach (var x in Lista_Maranhao)
                {
                    //Adiciona itens no combobox:
                    cbbMunicipio.Items.Add(x);
                }
            }

            else if (cbbEstado.Text == "Paraíba – PB")
            {
                cbbMunicipio.Items.Clear();
                //Foreach
                foreach (var x in Lista_Paraiba)
                {
                    //Adiciona itens no combobox:
                    cbbMunicipio.Items.Add(x);
                }
            }

            else if (cbbEstado.Text == "Pernambuco – PE")
            {
                cbbMunicipio.Items.Clear();
                //Foreach
                foreach (var x in Lista_Pernambuco)
                {
                    //Adiciona itens no combobox:
                    cbbMunicipio.Items.Add(x);
                }
            }

            else if (cbbEstado.Text == "Piauí – PI")
            {
                cbbMunicipio.Items.Clear();
                //Foreach
                foreach (var x in Lista_Piaui)
                {
                    //Adiciona itens no combobox:
                    cbbMunicipio.Items.Add(x);
                }
            }

            else if (cbbEstado.Text == "Rio Grande do Norte – RN")
            {
                cbbMunicipio.Items.Clear();
                //Foreach
                foreach (var x in Lista_RioGrandeNorte)
                {
                    //Adiciona itens no combobox:
                    cbbMunicipio.Items.Add(x);
                }
            }

            else if (cbbEstado.Text == "Sergipe – SE")
            {
                cbbMunicipio.Items.Clear();
                //Foreach
                foreach (var x in Lista_Sergipe)
                {
                    //Adiciona itens no combobox:
                    cbbMunicipio.Items.Add(x);
                }
            }
        }
        #endregion
    }
}